import { useEffect, useRef, useState } from "react";
import { Share2, Image as ImageIcon, FileText, Loader2, Download } from "lucide-react";
import { toPng } from "html-to-image";
import QRCode from "qrcode";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import {
  listCompanyTransactions,
  type CompanySummary,
  type PremiumTx,
} from "@/lib/swap-premium.functions";
import { logClientAuditEvent } from "@/lib/swap-audit.functions";

/* -------------------- i18n -------------------- */

type Lang = "en" | "ar" | "fr";
const LANG_KEY = "swap.dp.share.lang";

type Dict = {
  companySummary: string;
  goldDiscountBalance: string;
  company: string;
  snapshot: string;
  totalBalance: string;
  dpGold: string;
  totalDPUsd: string;
  availableNoDP: string;
  availableDesc: string;
  allTransactions: string;
  noTransactions: string;
  date: string;
  type: string;
  weight: string;
  notes: string;
  totalDP: string;
  confidential: string;
  scanVerify: string;
  generatedBy: string;
  txKinds: Record<PremiumTx["kind"], string>;
  premiumApplied: string;
  discountApplied: string;
  gold: string;
  value: string;
  // Dialog UI
  shareTitle: (name: string) => string;
  language: string;
  shareSummary: string;
  shareSummaryDesc: string;
  shareStatement: string;
  shareStatementDesc: string;
  fallbackNote: string;
  generatingSummary: string;
  generatingStatement: string;
  english: string;
  arabic: string;
  french: string;
};

const DICTS: Record<Lang, Dict> = {
  en: {
    companySummary: "Company Summary",
    goldDiscountBalance: "Gold Discount Balance",
    company: "Company",
    snapshot: "Snapshot",
    totalBalance: "Total Balance",
    dpGold: "Discount / Premium Gold",
    totalDPUsd: "Total Discount / Premium (USD)",
    availableNoDP: "Available — No D/P",
    availableDesc: "Total available gold after excluding Discount / Premium effect",
    allTransactions: "All Transactions",
    noTransactions: "No transactions recorded for this company.",
    date: "Date",
    type: "Type",
    weight: "Weight",
    notes: "Notes",
    totalDP: "Total Discount / Premium",
    confidential: "Confidential Client Report",
    scanVerify: "SCAN · VERIFY",
    generatedBy: "Generated by ATHER Desk · values reflect data at time of export.",
    txKinds: { add: "ADD", remove: "REMOVE", adjust: "ADJUST", discount: "DISCOUNT", premium: "PREMIUM" },
    premiumApplied: "Premium Applied",
    discountApplied: "Discount Applied",
    gold: "Gold",
    value: "Value",
    shareTitle: (n) => `Share ${n}`,
    language: "Language",
    shareSummary: "Share Company Summary",
    shareSummaryDesc: "One-page overview image",
    shareStatement: "Share Full Transaction Statement",
    shareStatementDesc: "Every transaction for this company",
    fallbackNote: "Falls back to download on devices without native share.",
    generatingSummary: "Generating summary…",
    generatingStatement: "Generating full statement…",
    english: "English",
    arabic: "Arabic",
    french: "French",
  },
  ar: {
    companySummary: "ملخص الشركة",
    goldDiscountBalance: "رصيد خصم الذهب",
    company: "الشركة",
    snapshot: "لقطة",
    totalBalance: "الرصيد الإجمالي",
    dpGold: "ذهب الخصم / العلاوة",
    totalDPUsd: "إجمالي الخصم / العلاوة (دولار)",
    availableNoDP: "المتاح — بدون خ/ع",
    availableDesc: "إجمالي الذهب المتاح بعد استبعاد أثر الخصم / العلاوة",
    allTransactions: "جميع المعاملات",
    noTransactions: "لا توجد معاملات مسجلة لهذه الشركة.",
    date: "التاريخ",
    type: "النوع",
    weight: "الوزن",
    notes: "ملاحظات",
    totalDP: "إجمالي الخصم / العلاوة",
    confidential: "تقرير عميل سري",
    scanVerify: "امسح · تحقق",
    generatedBy: "تم الإنشاء بواسطة ATHER Desk · القيم تعكس البيانات وقت التصدير.",
    txKinds: { add: "إضافة", remove: "إزالة", adjust: "تعديل", discount: "خصم", premium: "علاوة" },
    premiumApplied: "تم تطبيق العلاوة",
    discountApplied: "تم تطبيق الخصم",
    gold: "الذهب",
    value: "القيمة",
    shareTitle: (n) => `مشاركة ${n}`,
    language: "اللغة",
    shareSummary: "مشاركة ملخص الشركة",
    shareSummaryDesc: "صورة نظرة عامة من صفحة واحدة",
    shareStatement: "مشاركة كشف المعاملات الكامل",
    shareStatementDesc: "كل معاملة لهذه الشركة",
    fallbackNote: "يتم التنزيل تلقائيًا على الأجهزة التي لا تدعم المشاركة الأصلية.",
    generatingSummary: "جارٍ إنشاء الملخص…",
    generatingStatement: "جارٍ إنشاء الكشف الكامل…",
    english: "الإنجليزية",
    arabic: "العربية",
    french: "الفرنسية",
  },
  fr: {
    companySummary: "Résumé de la société",
    goldDiscountBalance: "Solde de remise sur l’or",
    company: "Société",
    snapshot: "Instantané",
    totalBalance: "Solde total",
    dpGold: "Or remise / prime",
    totalDPUsd: "Total remise / prime (USD)",
    availableNoDP: "Disponible — sans R/P",
    availableDesc: "Or total disponible après exclusion de l’effet remise / prime",
    allTransactions: "Toutes les transactions",
    noTransactions: "Aucune transaction enregistrée pour cette société.",
    date: "Date",
    type: "Type",
    weight: "Poids",
    notes: "Notes",
    totalDP: "Total remise / prime",
    confidential: "Rapport client confidentiel",
    scanVerify: "SCANNER · VÉRIFIER",
    generatedBy: "Généré par ATHER Desk · les valeurs reflètent les données au moment de l’export.",
    txKinds: { add: "AJOUT", remove: "RETRAIT", adjust: "AJUSTER", discount: "REMISE", premium: "PRIME" },
    premiumApplied: "Prime appliquée",
    discountApplied: "Remise appliquée",
    gold: "Or",
    value: "Valeur",
    shareTitle: (n) => `Partager ${n}`,
    language: "Langue",
    shareSummary: "Partager le résumé de la société",
    shareSummaryDesc: "Image de synthèse sur une page",
    shareStatement: "Partager le relevé complet",
    shareStatementDesc: "Toutes les transactions de cette société",
    fallbackNote: "Téléchargement automatique sur les appareils sans partage natif.",
    generatingSummary: "Génération du résumé…",
    generatingStatement: "Génération du relevé complet…",
    english: "Anglais",
    arabic: "Arabe",
    french: "Français",
  },
};

/* -------------------- Formatters -------------------- */

const fmtG = (n: number) =>
  `${(Number(n) || 0).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })} g`;

const fmtGNum = (n: number) =>
  (Number(n) || 0).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

const fmtUSD = (n: number) => {
  const v = Number(n) || 0;
  const abs = Math.abs(v);
  const s = abs.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return v < 0 ? `-$${s}` : `$${s}`;
};

const fmtDate = (d: string) => {
  const dt = new Date(d);
  if (isNaN(dt.getTime())) return d;
  const p = (n: number) => String(n).padStart(2, "0");
  return `${dt.getFullYear()}-${p(dt.getMonth() + 1)}-${p(dt.getDate())} ${p(dt.getHours())}:${p(dt.getMinutes())}:${p(dt.getSeconds())}`;
};

type Mode = "summary" | "statement";

/* -------------------- Brand tokens -------------------- */

const BG = "#1a1a1a";
const CARD = "#222222";
const CARD_2 = "#2a2a2a";
const BORDER = "#2f2f2f";
const BORDER_SOFT = "#2a2a2a";
const TEXT = "#f4f1ec";
const TEXT_MUTED = "#9a9a9a";
const TEXT_SOFT = "#d9d4cc";
const TEXT_FAINT = "#7a7a7a";
const EMBER = "#e85d3a";
const EMBER_DEEP = "#c64a2d";
const DANGER = "#ef4444";
const OK = "#22c55e";
const INFO = "#38bdf8";

const baseFont =
  "Epilogue, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
const displayFont = "Urbanist, " + baseFont;
const arabicFont =
  "'Noto Naskh Arabic', 'Amiri', 'Geeza Pro', 'Segoe UI', Tahoma, Arial, sans-serif";

const fontForLang = (lang: Lang) => (lang === "ar" ? arabicFont : baseFont);
const displayFontForLang = (lang: Lang) => (lang === "ar" ? arabicFont : displayFont);

const TX_COLOR: Record<PremiumTx["kind"], string> = {
  add: OK,
  remove: DANGER,
  adjust: INFO,
  discount: OK,
  premium: EMBER,
};

/** Build a single-line, professional note for discount/premium rows. */
function formatTxNote(t: PremiumTx, dict: Dict): string {
  if (t.kind === "discount" || t.kind === "premium") {
    const isPremium = t.kind === "premium";
    const label = isPremium ? dict.premiumApplied : dict.discountApplied;
    const sign = isPremium ? "+" : "-";
    const rate = Number(t.per_oz ?? 0).toFixed(0);
    const grams = (Number(t.grams) || 0).toLocaleString("en-US", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });
    const valueAbs = Math.abs(Number(t.amount_usd ?? 0)).toLocaleString("en-US", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });
    const base = `${label} (${sign}${rate} USD/oz) | ${dict.gold}: ${grams} g | ${dict.value}: $${valueAbs}`;
    return t.notes ? `${base} — ${t.notes}` : base;
  }
  return t.notes || "—";
}

/* -------------------- Component -------------------- */

export function ShareCompanyDialog({ summary }: { summary: CompanySummary }) {
  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState<Mode | null>(null);
  const [busy, setBusy] = useState(false);
  const [txs, setTxs] = useState<PremiumTx[] | null>(null);
  const [qr, setQr] = useState<string>("");
  const [lang, setLang] = useState<Lang>("en");
  const summaryRef = useRef<HTMLDivElement>(null);
  const statementRef = useRef<HTMLDivElement>(null);

  const dict = DICTS[lang];

  // Load persisted language preference
  useEffect(() => {
    if (typeof window === "undefined") return;
    const saved = window.localStorage.getItem(LANG_KEY);
    if (saved === "en" || saved === "ar" || saved === "fr") setLang(saved);
  }, []);

  const updateLang = (l: Lang) => {
    setLang(l);
    if (typeof window !== "undefined") {
      try {
        window.localStorage.setItem(LANG_KEY, l);
      } catch {
        /* ignore */
      }
    }
  };

  useEffect(() => {
    if (!open) return;
    const url =
      typeof window !== "undefined"
        ? `${window.location.origin}/desk/app/discount-premium`
        : "https://ather.group";
    QRCode.toDataURL(url, {
      margin: 0,
      width: 220,
      color: { dark: "#1a1a1a", light: "#ffffff" },
    })
      .then(setQr)
      .catch(() => setQr(""));
  }, [open]);

  useEffect(() => {
    if (open && !txs) {
      listCompanyTransactions({ data: { companyId: summary.company.id } })
        .then(setTxs)
        .catch(() => setTxs([]));
    }
  }, [open, summary.company.id, txs]);

  const triggerDownload = (dataUrl: string, fileName: string) => {
    const a = document.createElement("a");
    a.href = dataUrl;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const withTimeout = <T,>(p: Promise<T>, ms: number, label: string): Promise<T> =>
    new Promise((resolve, reject) => {
      const t = setTimeout(() => reject(new Error(`${label} timed out`)), ms);
      p.then(
        (v) => {
          clearTimeout(t);
          resolve(v);
        },
        (e) => {
          clearTimeout(t);
          reject(e);
        },
      );
    });

  const shareNode = async (
    node: HTMLDivElement,
    fileNameSuffix: string,
    _titleSuffix: string,
  ) => {
    const dataUrl = await withTimeout(
      toPng(node, { pixelRatio: 3, cacheBust: true, backgroundColor: BG }),
      30000,
      "Image generation",
    );
    const blob = await (await fetch(dataUrl)).blob();
    const fileName = `ATHER_${summary.company.name.replace(/[^a-z0-9]+/gi, "_")}_${fileNameSuffix}_${lang}.png`;
    const file = new File([blob], fileName, { type: "image/png" });
    const nav = navigator as Navigator & {
      canShare?: (d: { files?: File[] }) => boolean;
      share?: (d: ShareData & { files?: File[] }) => Promise<void>;
    };
    if (nav.share && nav.canShare && nav.canShare({ files: [file] })) {
      try {
        await nav.share({ files: [file] });
        toast.success("Shared");
      } catch (err) {
        if ((err as Error).name !== "AbortError") {
          triggerDownload(dataUrl, fileName);
          toast.success("Image saved");
        }
      }
    } else {
      triggerDownload(dataUrl, fileName);
      toast.success("Image downloaded");
    }
  };

  const audit = (action: string, status: "success" | "failure", details?: Record<string, unknown>) => {
    logClientAuditEvent({
      data: {
        module: "premium",
        action,
        status,
        entity_type: "premium_company",
        entity_id: summary.company.id,
        details: {
          company_name: summary.company.name,
          language: lang,
          ...details,
        },
      },
    }).catch(() => {});
  };

  const generateCompanySummaryImage = async () => {
    setMode("summary");
    setBusy(true);
    const toastId = toast.loading(dict.generatingSummary);
    try {
      await new Promise((r) => setTimeout(r, 120));
      const node = summaryRef.current;
      if (!node) throw new Error("Summary render node missing");
      await shareNode(node, "summary", "company summary");
      audit("company_summary_shared", "success");
    } catch (err) {
      console.error(err);
      const msg = err instanceof Error ? err.message : "Failed to generate summary";
      toast.error(msg);
      audit("company_summary_shared", "failure", { error: msg });
    } finally {
      toast.dismiss(toastId);
      setBusy(false);
      setMode(null);
    }
  };

  const generateFullTransactionStatement = async () => {
    setMode("statement");
    setBusy(true);
    const toastId = toast.loading(dict.generatingStatement);
    try {
      const all = await withTimeout(
        listCompanyTransactions({ data: { companyId: summary.company.id } }),
        20000,
        "Loading transactions",
      );
      setTxs(all);
      await new Promise((r) => setTimeout(r, 350));
      const node = statementRef.current;
      if (!node) throw new Error("Statement render node missing");
      await shareNode(node, "statement", "full transaction statement");
      audit("full_statement_shared", "success", { tx_count: all.length });
    } catch (err) {
      console.error(err);
      const msg = err instanceof Error ? err.message : "Failed to generate statement";
      toast.error(msg);
      audit("full_statement_shared", "failure", { error: msg });
    } finally {
      toast.dismiss(toastId);
      setBusy(false);
      setMode(null);
    }
  };

  const generatedAt = new Date().toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        setOpen(o);
        if (!o) {
          setMode(null);
          setTxs(null);
        }
      }}
    >
      <DialogTrigger asChild>
        <Button size="icon" variant="ghost" className="h-7 w-7" title="Share">
          <Share2 className="h-3.5 w-3.5 text-sky-400" />
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{dict.shareTitle(summary.company.name)}</DialogTitle>
        </DialogHeader>
        <div className="grid gap-3">
          <div className="grid gap-1.5">
            <Label htmlFor="dp-share-lang" className="text-xs">
              {dict.language}
            </Label>
            <Select value={lang} onValueChange={(v) => updateLang(v as Lang)}>
              <SelectTrigger id="dp-share-lang">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="en">{dict.english}</SelectItem>
                <SelectItem value="ar">{dict.arabic}</SelectItem>
                <SelectItem value="fr">{dict.french}</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <Button
            variant="outline"
            className="justify-start h-auto py-3"
            disabled={busy}
            onClick={generateCompanySummaryImage}
          >
            {busy && mode === "summary" ? (
              <Loader2 className="h-5 w-5 animate-spin mr-3" />
            ) : (
              <ImageIcon className="h-5 w-5 mr-3 text-primary" />
            )}
            <div className="text-left">
              <div className="font-semibold">
                {busy && mode === "summary" ? dict.generatingSummary : dict.shareSummary}
              </div>
              <div className="text-xs text-muted-foreground">{dict.shareSummaryDesc}</div>
            </div>
          </Button>
          <Button
            variant="outline"
            className="justify-start h-auto py-3"
            disabled={busy}
            onClick={generateFullTransactionStatement}
          >
            {busy && mode === "statement" ? (
              <Loader2 className="h-5 w-5 animate-spin mr-3" />
            ) : (
              <FileText className="h-5 w-5 mr-3 text-primary" />
            )}
            <div className="text-left">
              <div className="font-semibold">
                {busy && mode === "statement" ? dict.generatingStatement : dict.shareStatement}
              </div>
              <div className="text-xs text-muted-foreground">{dict.shareStatementDesc}</div>
            </div>
          </Button>
          <p className="text-[11px] text-muted-foreground flex items-center gap-1.5">
            <Download className="h-3 w-3" /> {dict.fallbackNote}
          </p>
        </div>

        {/* Hidden offscreen render targets */}
        <div
          aria-hidden
          style={{
            position: "fixed",
            top: 0,
            left: "-99999px",
            pointerEvents: "none",
            opacity: 1,
          }}
        >
          <SummaryCard
            ref={summaryRef}
            summary={summary}
            qr={qr}
            generatedAt={generatedAt}
            lang={lang}
            dict={dict}
          />
          {txs && (
            <StatementCard
              ref={statementRef}
              summary={summary}
              txs={txs}
              qr={qr}
              generatedAt={generatedAt}
              lang={lang}
              dict={dict}
            />
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

/* -------------------- Brand header -------------------- */

function Brand({ subtitle, lang }: { subtitle: string; lang: Lang }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
      <div
        style={{
          width: 38,
          height: 38,
          borderRadius: 8,
          background: `linear-gradient(135deg, ${EMBER}, ${EMBER_DEEP})`,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontWeight: 800,
          color: BG,
          fontSize: 18,
          fontFamily: displayFont,
        }}
      >
        A
      </div>
      <div>
        <div
          style={{
            fontFamily: displayFont,
            fontWeight: 800,
            letterSpacing: "-0.02em",
            fontSize: 18,
            lineHeight: 1,
            color: TEXT,
          }}
        >
          ATHER GROUP
        </div>
        <div
          style={{
            fontSize: 11,
            color: TEXT_MUTED,
            letterSpacing: lang === "ar" ? "0" : "0.14em",
            textTransform: lang === "ar" ? "none" : "uppercase",
            marginTop: 3,
            fontFamily: displayFontForLang(lang),
          }}
        >
          {subtitle}
        </div>
      </div>
    </div>
  );
}

function CompanyHeader({
  name,
  generatedAt,
  lang,
  dict,
}: {
  name: string;
  generatedAt: string;
  lang: Lang;
  dict: Dict;
}) {
  const isRTL = lang === "ar";
  return (
    <div
      style={{
        marginTop: 22,
        display: "flex",
        justifyContent: "space-between",
        gap: 16,
      }}
    >
      <div>
        <div
          style={{
            fontSize: 11,
            color: TEXT_MUTED,
            letterSpacing: isRTL ? "0" : "0.08em",
            textTransform: isRTL ? "none" : "uppercase",
            fontFamily: fontForLang(lang),
          }}
        >
          {dict.company}
        </div>
        <div
          style={{
            fontSize: 22,
            fontWeight: 700,
            marginTop: 2,
            letterSpacing: "-0.01em",
            color: TEXT,
            fontFamily: displayFontForLang(lang),
          }}
        >
          {name}
        </div>
      </div>
      <div style={{ textAlign: isRTL ? "left" : "right" }}>
        <div
          style={{
            fontSize: 11,
            color: TEXT_MUTED,
            letterSpacing: isRTL ? "0" : "0.08em",
            textTransform: isRTL ? "none" : "uppercase",
            fontFamily: fontForLang(lang),
          }}
        >
          {dict.snapshot}
        </div>
        <div
          style={{
            fontSize: 13,
            color: TEXT_SOFT,
            marginTop: 4,
            fontFamily: baseFont,
            direction: "ltr",
          }}
        >
          {generatedAt}
        </div>
      </div>
    </div>
  );
}

function Row({
  label,
  value,
  valueColor,
  emphasize,
  lang,
}: {
  label: string;
  value: string;
  valueColor?: string;
  emphasize?: boolean;
  lang: Lang;
}) {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "space-between",
        alignItems: "baseline",
        padding: "10px 0",
        borderBottom: emphasize ? "none" : `1px solid ${BORDER_SOFT}`,
      }}
    >
      <span
        style={{
          fontSize: 13,
          color: TEXT_MUTED,
          letterSpacing: "0.02em",
          fontFamily: fontForLang(lang),
        }}
      >
        {label}
      </span>
      <span
        style={{
          fontSize: emphasize ? 20 : 15,
          color: valueColor ?? TEXT,
          fontWeight: emphasize ? 700 : 600,
          fontVariantNumeric: "tabular-nums",
          direction: "ltr",
        }}
      >
        {value}
      </span>
    </div>
  );
}

function BrandFooter({ qr, lang, dict }: { qr: string; lang: Lang; dict: Dict }) {
  const isRTL = lang === "ar";
  return (
    <div
      style={{
        marginTop: 22,
        paddingTop: 16,
        borderTop: `1px solid ${BORDER_SOFT}`,
        display: "grid",
        gridTemplateColumns: "72px 1fr 72px",
        alignItems: "center",
        gap: 16,
        direction: "ltr",
      }}
    >
      <div />
      <div style={{ textAlign: "center" }}>
        <div
          style={{
            fontFamily: displayFont,
            fontWeight: 800,
            letterSpacing: "0.04em",
            fontSize: 13,
            color: TEXT_SOFT,
          }}
        >
          ATHER GROUP
        </div>
        <div
          style={{
            fontSize: 10,
            color: TEXT_FAINT,
            letterSpacing: isRTL ? "0" : "0.14em",
            textTransform: isRTL ? "none" : "uppercase",
            marginTop: 4,
            fontFamily: fontForLang(lang),
          }}
        >
          {dict.confidential}
        </div>
        <div
          style={{
            fontSize: 10,
            color: TEXT_FAINT,
            fontStyle: "italic",
            marginTop: 6,
            fontFamily: fontForLang(lang),
          }}
        >
          {dict.generatedBy}
        </div>
      </div>
      <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifySelf: "end" }}>
        {qr ? (
          <>
            <img
              src={qr}
              alt=""
              style={{
                width: 64,
                height: 64,
                borderRadius: 6,
                background: "#fff",
                padding: 3,
              }}
            />
            <div
              style={{
                fontSize: 8,
                color: TEXT_FAINT,
                marginTop: 4,
                letterSpacing: "0.14em",
                fontFamily: fontForLang(lang),
              }}
            >
              {dict.scanVerify}
            </div>
          </>
        ) : null}
      </div>
    </div>
  );
}

/* -------------------- Available (no D/P) hero highlight -------------------- */

function AvailableHighlight({ grams, lang, dict }: { grams: number; lang: Lang; dict: Dict }) {
  const positive = grams >= 0;
  const color = positive ? OK : DANGER;
  const isRTL = lang === "ar";
  return (
    <div
      style={{
        marginTop: 18,
        padding: "26px 24px",
        background: CARD,
        border: `2px solid ${color}`,
        borderRadius: 14,
        textAlign: "center",
        boxShadow: `0 0 0 4px ${color}22 inset`,
      }}
    >
      <div
        style={{
          fontSize: 12,
          color: TEXT_MUTED,
          letterSpacing: isRTL ? "0" : "0.18em",
          textTransform: isRTL ? "none" : "uppercase",
          fontWeight: 700,
          fontFamily: fontForLang(lang),
        }}
      >
        {dict.availableNoDP}
      </div>
      <div
        style={{
          fontSize: 11,
          color: TEXT_FAINT,
          marginTop: 4,
          fontFamily: fontForLang(lang),
        }}
      >
        {dict.availableDesc}
      </div>
      <div
        style={{
          fontSize: 48,
          fontWeight: 900,
          marginTop: 12,
          fontVariantNumeric: "tabular-nums",
          letterSpacing: "-0.02em",
          color,
          fontFamily: displayFont,
          lineHeight: 1,
          direction: "ltr",
        }}
      >
        {fmtGNum(grams)}
        <span
          style={{
            fontSize: 22,
            color,
            marginLeft: 10,
            fontWeight: 700,
            opacity: 0.85,
          }}
        >
          g
        </span>
      </div>
    </div>
  );
}

/* -------------------- Summary card -------------------- */

const SummaryCard = ({
  ref,
  summary,
  qr,
  generatedAt,
  lang,
  dict,
}: {
  ref: React.RefObject<HTMLDivElement | null>;
  summary: CompanySummary;
  qr: string;
  generatedAt: string;
  lang: Lang;
  dict: Dict;
}) => {
  const isRTL = lang === "ar";
  return (
    <div
      ref={ref}
      dir={isRTL ? "rtl" : "ltr"}
      style={{
        width: 780,
        background: BG,
        color: TEXT,
        fontFamily: fontForLang(lang),
        padding: "32px 36px 28px",
      }}
    >
      <Brand subtitle={dict.companySummary} lang={lang} />
      <CompanyHeader name={summary.company.name} generatedAt={generatedAt} lang={lang} dict={dict} />

      <div
        style={{
          marginTop: 18,
          padding: "4px 16px",
          background: CARD,
          border: `1px solid ${BORDER}`,
          borderRadius: 10,
        }}
      >
        <Row
          label={dict.totalBalance}
          value={fmtG(summary.total_balance_grams)}
          valueColor={summary.total_balance_grams < 0 ? DANGER : undefined}
          lang={lang}
        />
        <Row
          label={dict.dpGold}
          value={fmtG(summary.dp_grams)}
          valueColor={EMBER}
          lang={lang}
        />
        <Row
          label={dict.totalDPUsd}
          value={fmtUSD(summary.dp_charges_usd)}
          valueColor={summary.dp_charges_usd < 0 ? DANGER : OK}
          emphasize
          lang={lang}
        />
      </div>

      <AvailableHighlight grams={summary.clean_remaining_grams} lang={lang} dict={dict} />

      <BrandFooter qr={qr} lang={lang} dict={dict} />
    </div>
  );
};

/* -------------------- Full transaction statement -------------------- */

const StatementCard = ({
  ref,
  summary,
  txs,
  qr,
  generatedAt,
  lang,
  dict,
}: {
  ref: React.RefObject<HTMLDivElement | null>;
  summary: CompanySummary;
  txs: PremiumTx[];
  qr: string;
  generatedAt: string;
  lang: Lang;
  dict: Dict;
}) => {
  const all = [...txs].sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime(),
  );
  const isRTL = lang === "ar";

  return (
    <div
      ref={ref}
      dir={isRTL ? "rtl" : "ltr"}
      style={{
        width: 880,
        background: BG,
        color: TEXT,
        fontFamily: fontForLang(lang),
        padding: "32px 36px 28px",
      }}
    >
      <Brand subtitle={dict.goldDiscountBalance} lang={lang} />
      <CompanyHeader name={summary.company.name} generatedAt={generatedAt} lang={lang} dict={dict} />

      <div style={{ marginTop: 18 }}>
        <div
          style={{
            fontSize: 11,
            color: TEXT_MUTED,
            letterSpacing: isRTL ? "0" : "0.14em",
            textTransform: isRTL ? "none" : "uppercase",
            marginBottom: 8,
            fontFamily: fontForLang(lang),
          }}
        >
          — {dict.allTransactions} ({all.length}) —
        </div>

        {all.length === 0 ? (
          <div
            style={{
              padding: 18,
              textAlign: "center",
              color: TEXT_MUTED,
              fontSize: 13,
              background: CARD,
              border: `1px solid ${BORDER}`,
              borderRadius: 10,
              fontFamily: fontForLang(lang),
            }}
          >
            {dict.noTransactions}
          </div>
        ) : (
          <div
            style={{
              background: CARD,
              border: `1px solid ${BORDER}`,
              borderRadius: 10,
              overflow: "hidden",
            }}
          >
            <table
              style={{
                width: "100%",
                borderCollapse: "collapse",
                tableLayout: "fixed",
                fontVariantNumeric: "tabular-nums",
              }}
            >
              <colgroup>
                <col style={{ width: "20%" }} />
                <col style={{ width: "12%" }} />
                <col style={{ width: "15%" }} />
                <col style={{ width: "53%" }} />
              </colgroup>
              <thead>
                <tr style={{ background: CARD_2 }}>
                  <th style={{ textAlign: isRTL ? "right" : "left", padding: "12px 16px", fontSize: 10, color: TEXT_MUTED, letterSpacing: isRTL ? "0" : "0.1em", textTransform: isRTL ? "none" : "uppercase", fontWeight: 700, fontFamily: fontForLang(lang) }}>{dict.date}</th>
                  <th style={{ textAlign: isRTL ? "right" : "left", padding: "12px 16px", fontSize: 10, color: TEXT_MUTED, letterSpacing: isRTL ? "0" : "0.1em", textTransform: isRTL ? "none" : "uppercase", fontWeight: 700, fontFamily: fontForLang(lang) }}>{dict.type}</th>
                  <th style={{ textAlign: isRTL ? "left" : "right", padding: "12px 16px", fontSize: 10, color: TEXT_MUTED, letterSpacing: isRTL ? "0" : "0.1em", textTransform: isRTL ? "none" : "uppercase", fontWeight: 700, fontFamily: fontForLang(lang) }}>{dict.weight}</th>
                  <th style={{ textAlign: isRTL ? "right" : "left", padding: "12px 18px", fontSize: 10, color: TEXT_MUTED, letterSpacing: isRTL ? "0" : "0.1em", textTransform: isRTL ? "none" : "uppercase", fontWeight: 700, fontFamily: fontForLang(lang) }}>{dict.notes}</th>
                </tr>
              </thead>
              <tbody>
                {all.map((t) => (
                  <tr key={t.id} style={{ borderTop: `1px solid ${BORDER_SOFT}` }}>
                    <td style={{ padding: "12px 16px", verticalAlign: "middle", color: TEXT_SOFT, fontSize: 11, whiteSpace: "nowrap", direction: "ltr", textAlign: isRTL ? "right" : "left" }}>
                      {fmtDate(t.created_at)}
                    </td>
                    <td style={{ padding: "12px 16px", verticalAlign: "middle", fontSize: 10, fontWeight: 800, letterSpacing: isRTL ? "0" : "0.12em", color: TX_COLOR[t.kind], whiteSpace: "nowrap", fontFamily: fontForLang(lang) }}>
                      {dict.txKinds[t.kind]}
                    </td>
                    <td style={{ padding: "12px 16px", verticalAlign: "middle", textAlign: isRTL ? "left" : "right", color: TEXT, fontSize: 12, fontWeight: 600, whiteSpace: "nowrap", direction: "ltr" }}>
                      {fmtGNum(Number(t.grams))} g
                    </td>
                    <td style={{ padding: "12px 18px", verticalAlign: "middle", color: TEXT_SOFT, fontSize: 11, lineHeight: 1.55, wordBreak: "break-word", overflowWrap: "anywhere", fontFamily: fontForLang(lang) }}>
                      {formatTxNote(t, dict)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Total Discount / Premium */}
      <div
        style={{
          marginTop: 16,
          padding: "18px 22px",
          background: CARD,
          border: `1px solid ${BORDER}`,
          borderRadius: 10,
          textAlign: "center",
        }}
      >
        <div
          style={{
            fontSize: 11,
            color: TEXT_MUTED,
            letterSpacing: isRTL ? "0" : "0.18em",
            textTransform: isRTL ? "none" : "uppercase",
            fontWeight: 700,
            fontFamily: fontForLang(lang),
          }}
        >
          {dict.totalDP}
        </div>
        <div
          style={{
            marginTop: 10,
            display: "flex",
            justifyContent: "center",
            alignItems: "baseline",
            gap: 28,
            flexWrap: "wrap",
            direction: "ltr",
          }}
        >
          <div
            style={{
              fontSize: 22,
              fontWeight: 800,
              color: TEXT,
              fontVariantNumeric: "tabular-nums",
              fontFamily: displayFont,
              letterSpacing: "-0.01em",
            }}
          >
            {fmtG(summary.dp_grams)}
          </div>
          <div
            style={{
              fontSize: 22,
              fontWeight: 800,
              color: summary.dp_charges_usd < 0 ? DANGER : OK,
              fontVariantNumeric: "tabular-nums",
              fontFamily: displayFont,
              letterSpacing: "-0.01em",
            }}
          >
            {fmtUSD(summary.dp_charges_usd)}
          </div>
        </div>
      </div>

      <AvailableHighlight grams={summary.clean_remaining_grams} lang={lang} dict={dict} />

      <BrandFooter qr={qr} lang={lang} dict={dict} />
    </div>
  );
};
