/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as MarginRouteImport } from './routes/margin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SwapIndexRouteImport } from './routes/swap/index'
import { Route as PurityIndexRouteImport } from './routes/purity/index'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as SwapDashboardRouteImport } from './routes/swap/dashboard'
import { Route as PurityDashboardRouteImport } from './routes/purity/dashboard'
import { Route as DeskLoginRouteImport } from './routes/desk.login'
import { Route as DeskAppIndexRouteImport } from './routes/desk.app.index'
import { Route as SwapClientsClientIdRouteImport } from './routes/swap/clients.$clientId'
import { Route as PurityTripsTripIdRouteImport } from './routes/purity/trips.$tripId'
import { Route as DeskAppUsersRouteImport } from './routes/desk.app.users'
import { Route as DeskAppSwapRouteImport } from './routes/desk.app.swap'
import { Route as DeskAppSettingsRouteImport } from './routes/desk.app.settings'
import { Route as DeskAppReportsRouteImport } from './routes/desk.app.reports'
import { Route as DeskAppPurityRouteImport } from './routes/desk.app.purity'
import { Route as DeskAppMarginRouteImport } from './routes/desk.app.margin'
import { Route as DeskAppDiscountPremiumRouteImport } from './routes/desk.app.discount-premium'
import { Route as DeskAppDashboardRouteImport } from './routes/desk.app.dashboard'
import { Route as DeskAppAuditRouteImport } from './routes/desk.app.audit'
import { Route as ApiPublicHooksSwapDailyFeesRouteImport } from './routes/api/public/hooks/swap-daily-fees'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const MarginRoute = MarginRouteImport.update({
  id: '/margin',
  path: '/margin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapIndexRoute = SwapIndexRouteImport.update({
  id: '/swap/',
  path: '/swap/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurityIndexRoute = PurityIndexRouteImport.update({
  id: '/purity/',
  path: '/purity/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/desk/',
  path: '/desk/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapDashboardRoute = SwapDashboardRouteImport.update({
  id: '/swap/dashboard',
  path: '/swap/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PurityDashboardRoute = PurityDashboardRouteImport.update({
  id: '/purity/dashboard',
  path: '/purity/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskLoginRoute = DeskLoginRouteImport.update({
  id: '/desk/login',
  path: '/desk/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppIndexRoute = DeskAppIndexRouteImport.update({
  id: '/desk/app/',
  path: '/desk/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapClientsClientIdRoute = SwapClientsClientIdRouteImport.update({
  id: '/swap/clients/$clientId',
  path: '/swap/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PurityTripsTripIdRoute = PurityTripsTripIdRouteImport.update({
  id: '/purity/trips/$tripId',
  path: '/purity/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppUsersRoute = DeskAppUsersRouteImport.update({
  id: '/desk/app/users',
  path: '/desk/app/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppSwapRoute = DeskAppSwapRouteImport.update({
  id: '/desk/app/swap',
  path: '/desk/app/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppSettingsRoute = DeskAppSettingsRouteImport.update({
  id: '/desk/app/settings',
  path: '/desk/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppReportsRoute = DeskAppReportsRouteImport.update({
  id: '/desk/app/reports',
  path: '/desk/app/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppPurityRoute = DeskAppPurityRouteImport.update({
  id: '/desk/app/purity',
  path: '/desk/app/purity',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppMarginRoute = DeskAppMarginRouteImport.update({
  id: '/desk/app/margin',
  path: '/desk/app/margin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppDiscountPremiumRoute = DeskAppDiscountPremiumRouteImport.update({
  id: '/desk/app/discount-premium',
  path: '/desk/app/discount-premium',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppDashboardRoute = DeskAppDashboardRouteImport.update({
  id: '/desk/app/dashboard',
  path: '/desk/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAppAuditRoute = DeskAppAuditRouteImport.update({
  id: '/desk/app/audit',
  path: '/desk/app/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSwapDailyFeesRoute =
  ApiPublicHooksSwapDailyFeesRouteImport.update({
    id: '/api/public/hooks/swap-daily-fees',
    path: '/api/public/hooks/swap-daily-fees',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/margin': typeof MarginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/desk/login': typeof DeskLoginRoute
  '/purity/dashboard': typeof PurityDashboardRoute
  '/swap/dashboard': typeof SwapDashboardRoute
  '/desk/': typeof DeskIndexRoute
  '/purity/': typeof PurityIndexRoute
  '/swap/': typeof SwapIndexRoute
  '/desk/app/audit': typeof DeskAppAuditRoute
  '/desk/app/dashboard': typeof DeskAppDashboardRoute
  '/desk/app/discount-premium': typeof DeskAppDiscountPremiumRoute
  '/desk/app/margin': typeof DeskAppMarginRoute
  '/desk/app/purity': typeof DeskAppPurityRoute
  '/desk/app/reports': typeof DeskAppReportsRoute
  '/desk/app/settings': typeof DeskAppSettingsRoute
  '/desk/app/swap': typeof DeskAppSwapRoute
  '/desk/app/users': typeof DeskAppUsersRoute
  '/purity/trips/$tripId': typeof PurityTripsTripIdRoute
  '/swap/clients/$clientId': typeof SwapClientsClientIdRoute
  '/desk/app/': typeof DeskAppIndexRoute
  '/api/public/hooks/swap-daily-fees': typeof ApiPublicHooksSwapDailyFeesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/margin': typeof MarginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/desk/login': typeof DeskLoginRoute
  '/purity/dashboard': typeof PurityDashboardRoute
  '/swap/dashboard': typeof SwapDashboardRoute
  '/desk': typeof DeskIndexRoute
  '/purity': typeof PurityIndexRoute
  '/swap': typeof SwapIndexRoute
  '/desk/app/audit': typeof DeskAppAuditRoute
  '/desk/app/dashboard': typeof DeskAppDashboardRoute
  '/desk/app/discount-premium': typeof DeskAppDiscountPremiumRoute
  '/desk/app/margin': typeof DeskAppMarginRoute
  '/desk/app/purity': typeof DeskAppPurityRoute
  '/desk/app/reports': typeof DeskAppReportsRoute
  '/desk/app/settings': typeof DeskAppSettingsRoute
  '/desk/app/swap': typeof DeskAppSwapRoute
  '/desk/app/users': typeof DeskAppUsersRoute
  '/purity/trips/$tripId': typeof PurityTripsTripIdRoute
  '/swap/clients/$clientId': typeof SwapClientsClientIdRoute
  '/desk/app': typeof DeskAppIndexRoute
  '/api/public/hooks/swap-daily-fees': typeof ApiPublicHooksSwapDailyFeesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/margin': typeof MarginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/desk/login': typeof DeskLoginRoute
  '/purity/dashboard': typeof PurityDashboardRoute
  '/swap/dashboard': typeof SwapDashboardRoute
  '/desk/': typeof DeskIndexRoute
  '/purity/': typeof PurityIndexRoute
  '/swap/': typeof SwapIndexRoute
  '/desk/app/audit': typeof DeskAppAuditRoute
  '/desk/app/dashboard': typeof DeskAppDashboardRoute
  '/desk/app/discount-premium': typeof DeskAppDiscountPremiumRoute
  '/desk/app/margin': typeof DeskAppMarginRoute
  '/desk/app/purity': typeof DeskAppPurityRoute
  '/desk/app/reports': typeof DeskAppReportsRoute
  '/desk/app/settings': typeof DeskAppSettingsRoute
  '/desk/app/swap': typeof DeskAppSwapRoute
  '/desk/app/users': typeof DeskAppUsersRoute
  '/purity/trips/$tripId': typeof PurityTripsTripIdRoute
  '/swap/clients/$clientId': typeof SwapClientsClientIdRoute
  '/desk/app/': typeof DeskAppIndexRoute
  '/api/public/hooks/swap-daily-fees': typeof ApiPublicHooksSwapDailyFeesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/companies'
    | '/contact'
    | '/login'
    | '/margin'
    | '/unauthorized'
    | '/desk/login'
    | '/purity/dashboard'
    | '/swap/dashboard'
    | '/desk/'
    | '/purity/'
    | '/swap/'
    | '/desk/app/audit'
    | '/desk/app/dashboard'
    | '/desk/app/discount-premium'
    | '/desk/app/margin'
    | '/desk/app/purity'
    | '/desk/app/reports'
    | '/desk/app/settings'
    | '/desk/app/swap'
    | '/desk/app/users'
    | '/purity/trips/$tripId'
    | '/swap/clients/$clientId'
    | '/desk/app/'
    | '/api/public/hooks/swap-daily-fees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/companies'
    | '/contact'
    | '/login'
    | '/margin'
    | '/unauthorized'
    | '/desk/login'
    | '/purity/dashboard'
    | '/swap/dashboard'
    | '/desk'
    | '/purity'
    | '/swap'
    | '/desk/app/audit'
    | '/desk/app/dashboard'
    | '/desk/app/discount-premium'
    | '/desk/app/margin'
    | '/desk/app/purity'
    | '/desk/app/reports'
    | '/desk/app/settings'
    | '/desk/app/swap'
    | '/desk/app/users'
    | '/purity/trips/$tripId'
    | '/swap/clients/$clientId'
    | '/desk/app'
    | '/api/public/hooks/swap-daily-fees'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/companies'
    | '/contact'
    | '/login'
    | '/margin'
    | '/unauthorized'
    | '/desk/login'
    | '/purity/dashboard'
    | '/swap/dashboard'
    | '/desk/'
    | '/purity/'
    | '/swap/'
    | '/desk/app/audit'
    | '/desk/app/dashboard'
    | '/desk/app/discount-premium'
    | '/desk/app/margin'
    | '/desk/app/purity'
    | '/desk/app/reports'
    | '/desk/app/settings'
    | '/desk/app/swap'
    | '/desk/app/users'
    | '/purity/trips/$tripId'
    | '/swap/clients/$clientId'
    | '/desk/app/'
    | '/api/public/hooks/swap-daily-fees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MarginRoute: typeof MarginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DeskLoginRoute: typeof DeskLoginRoute
  PurityDashboardRoute: typeof PurityDashboardRoute
  SwapDashboardRoute: typeof SwapDashboardRoute
  DeskIndexRoute: typeof DeskIndexRoute
  PurityIndexRoute: typeof PurityIndexRoute
  SwapIndexRoute: typeof SwapIndexRoute
  DeskAppAuditRoute: typeof DeskAppAuditRoute
  DeskAppDashboardRoute: typeof DeskAppDashboardRoute
  DeskAppDiscountPremiumRoute: typeof DeskAppDiscountPremiumRoute
  DeskAppMarginRoute: typeof DeskAppMarginRoute
  DeskAppPurityRoute: typeof DeskAppPurityRoute
  DeskAppReportsRoute: typeof DeskAppReportsRoute
  DeskAppSettingsRoute: typeof DeskAppSettingsRoute
  DeskAppSwapRoute: typeof DeskAppSwapRoute
  DeskAppUsersRoute: typeof DeskAppUsersRoute
  PurityTripsTripIdRoute: typeof PurityTripsTripIdRoute
  SwapClientsClientIdRoute: typeof SwapClientsClientIdRoute
  DeskAppIndexRoute: typeof DeskAppIndexRoute
  ApiPublicHooksSwapDailyFeesRoute: typeof ApiPublicHooksSwapDailyFeesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margin': {
      id: '/margin'
      path: '/margin'
      fullPath: '/margin'
      preLoaderRoute: typeof MarginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/': {
      id: '/swap/'
      path: '/swap'
      fullPath: '/swap/'
      preLoaderRoute: typeof SwapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purity/': {
      id: '/purity/'
      path: '/purity'
      fullPath: '/purity/'
      preLoaderRoute: typeof PurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/desk'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/dashboard': {
      id: '/swap/dashboard'
      path: '/swap/dashboard'
      fullPath: '/swap/dashboard'
      preLoaderRoute: typeof SwapDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purity/dashboard': {
      id: '/purity/dashboard'
      path: '/purity/dashboard'
      fullPath: '/purity/dashboard'
      preLoaderRoute: typeof PurityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/login': {
      id: '/desk/login'
      path: '/desk/login'
      fullPath: '/desk/login'
      preLoaderRoute: typeof DeskLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/': {
      id: '/desk/app/'
      path: '/desk/app'
      fullPath: '/desk/app/'
      preLoaderRoute: typeof DeskAppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/clients/$clientId': {
      id: '/swap/clients/$clientId'
      path: '/swap/clients/$clientId'
      fullPath: '/swap/clients/$clientId'
      preLoaderRoute: typeof SwapClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purity/trips/$tripId': {
      id: '/purity/trips/$tripId'
      path: '/purity/trips/$tripId'
      fullPath: '/purity/trips/$tripId'
      preLoaderRoute: typeof PurityTripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/users': {
      id: '/desk/app/users'
      path: '/desk/app/users'
      fullPath: '/desk/app/users'
      preLoaderRoute: typeof DeskAppUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/swap': {
      id: '/desk/app/swap'
      path: '/desk/app/swap'
      fullPath: '/desk/app/swap'
      preLoaderRoute: typeof DeskAppSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/settings': {
      id: '/desk/app/settings'
      path: '/desk/app/settings'
      fullPath: '/desk/app/settings'
      preLoaderRoute: typeof DeskAppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/reports': {
      id: '/desk/app/reports'
      path: '/desk/app/reports'
      fullPath: '/desk/app/reports'
      preLoaderRoute: typeof DeskAppReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/purity': {
      id: '/desk/app/purity'
      path: '/desk/app/purity'
      fullPath: '/desk/app/purity'
      preLoaderRoute: typeof DeskAppPurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/margin': {
      id: '/desk/app/margin'
      path: '/desk/app/margin'
      fullPath: '/desk/app/margin'
      preLoaderRoute: typeof DeskAppMarginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/discount-premium': {
      id: '/desk/app/discount-premium'
      path: '/desk/app/discount-premium'
      fullPath: '/desk/app/discount-premium'
      preLoaderRoute: typeof DeskAppDiscountPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/dashboard': {
      id: '/desk/app/dashboard'
      path: '/desk/app/dashboard'
      fullPath: '/desk/app/dashboard'
      preLoaderRoute: typeof DeskAppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/app/audit': {
      id: '/desk/app/audit'
      path: '/desk/app/audit'
      fullPath: '/desk/app/audit'
      preLoaderRoute: typeof DeskAppAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/swap-daily-fees': {
      id: '/api/public/hooks/swap-daily-fees'
      path: '/api/public/hooks/swap-daily-fees'
      fullPath: '/api/public/hooks/swap-daily-fees'
      preLoaderRoute: typeof ApiPublicHooksSwapDailyFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MarginRoute: MarginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DeskLoginRoute: DeskLoginRoute,
  PurityDashboardRoute: PurityDashboardRoute,
  SwapDashboardRoute: SwapDashboardRoute,
  DeskIndexRoute: DeskIndexRoute,
  PurityIndexRoute: PurityIndexRoute,
  SwapIndexRoute: SwapIndexRoute,
  DeskAppAuditRoute: DeskAppAuditRoute,
  DeskAppDashboardRoute: DeskAppDashboardRoute,
  DeskAppDiscountPremiumRoute: DeskAppDiscountPremiumRoute,
  DeskAppMarginRoute: DeskAppMarginRoute,
  DeskAppPurityRoute: DeskAppPurityRoute,
  DeskAppReportsRoute: DeskAppReportsRoute,
  DeskAppSettingsRoute: DeskAppSettingsRoute,
  DeskAppSwapRoute: DeskAppSwapRoute,
  DeskAppUsersRoute: DeskAppUsersRoute,
  PurityTripsTripIdRoute: PurityTripsTripIdRoute,
  SwapClientsClientIdRoute: SwapClientsClientIdRoute,
  DeskAppIndexRoute: DeskAppIndexRoute,
  ApiPublicHooksSwapDailyFeesRoute: ApiPublicHooksSwapDailyFeesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
