REVOKE EXECUTE ON FUNCTION public.can_access_refinery(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_module_permission(uuid, app_module, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_platform_admin(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_purity_user(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_refinery_admin(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_swap_user(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_create_buysell(uuid, uuid, text, text, numeric, numeric, numeric, date, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_create_buysell(uuid, uuid, text, text, numeric, numeric, numeric, date, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_create_settlement(uuid, uuid, uuid, text, numeric, boolean, numeric, numeric, date, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_create_stock_adjustment(uuid, text, text, numeric, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_delete_settlement(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_delete_stock_adjustment(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_edit_settlement(uuid, uuid, uuid, text, numeric, boolean, numeric, numeric, date, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_edit_stock_adjustment(uuid, text, text, numeric, date, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_generate_client_code(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_restore_from_payload(uuid, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_reverse_transaction(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_settle_transaction(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_tx_auto_settle() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refinery_users_prevent_self_escalation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.user_refinery_id(uuid) FROM PUBLIC;